name: ci
on:
  push:
  pull_request:
  schedule:
  - cron:  '0 12 * * 1' # 12pm Monday
jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        toolchain: [nightly, stable]

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
    - run: cargo fmt -- --check
    - run: cargo clippy
    - run: cargo build
    - run: cargo test
